# Generated by Django 5.1 on 2024-08-29 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_color_varient_cartitems_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='size_varient',
            new_name='size_variant',
        ),
    ]
