# Generated by Django 5.1 on 2024-08-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_colorvarient_sizevariennt_product_color_varient_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorVarient',
            new_name='ColorVariant',
        ),
        migrations.RenameModel(
            old_name='SizeVariennt',
            new_name='SizeVariannt',
        ),
    ]
