# Generated by Django 5.1 on 2024-08-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_colorvarient_colorvariant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVariannt',
            new_name='SizeVariant',
        ),
    ]
